name: Cleanup old Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images

    permissions:
      packages: write

    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: tangram-orchestre
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "showcase-website"
          image-tags: "!latest"
          cut-off: 1d
